default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: openid_rails_poc_development

test:
  <<: *default
  database: openid_rails_poc_test

production:
  <<: *default
  database: openid_rails_poc_production
  username: openid_rails_poc
  password: <%= ENV['OPENID_RAILS_POC_DATABASE_PASSWORD'] %>
